// Mapa: nome em inglês (openfootball) -> código FIFA, nome pt-BR e bandeira.
export const TEAMS_PT_BR: Record<string, { fifaCode: string; name: string; flag: string }> = {
  'Mexico': { fifaCode: 'MEX', name: 'México', flag: '🇲🇽' },
  'South Africa': { fifaCode: 'RSA', name: 'África do Sul', flag: '🇿🇦' },
  'South Korea': { fifaCode: 'KOR', name: 'Coreia do Sul', flag: '🇰🇷' },
  'Czech Republic': { fifaCode: 'CZE', name: 'Tchéquia', flag: '🇨🇿' },
  'Canada': { fifaCode: 'CAN', name: 'Canadá', flag: '🇨🇦' },
  'Bosnia & Herzegovina': { fifaCode: 'BIH', name: 'Bósnia e Herzegovina', flag: '🇧🇦' },
  'Qatar': { fifaCode: 'QAT', name: 'Catar', flag: '🇶🇦' },
  'Switzerland': { fifaCode: 'SUI', name: 'Suíça', flag: '🇨🇭' },
  'Brazil': { fifaCode: 'BRA', name: 'Brasil', flag: '🇧🇷' },
  'Morocco': { fifaCode: 'MAR', name: 'Marrocos', flag: '🇲🇦' },
  'Haiti': { fifaCode: 'HAI', name: 'Haiti', flag: '🇭🇹' },
  'Scotland': { fifaCode: 'SCO', name: 'Escócia', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  'USA': { fifaCode: 'USA', name: 'Estados Unidos', flag: '🇺🇸' },
  'Paraguay': { fifaCode: 'PAR', name: 'Paraguai', flag: '🇵🇾' },
  'Australia': { fifaCode: 'AUS', name: 'Austrália', flag: '🇦🇺' },
  'Turkey': { fifaCode: 'TUR', name: 'Turquia', flag: '🇹🇷' },
  'Germany': { fifaCode: 'GER', name: 'Alemanha', flag: '🇩🇪' },
  'Curaçao': { fifaCode: 'CUW', name: 'Curaçao', flag: '🇨🇼' },
  'Ivory Coast': { fifaCode: 'CIV', name: 'Costa do Marfim', flag: '🇨🇮' },
  'Ecuador': { fifaCode: 'ECU', name: 'Equador', flag: '🇪🇨' },
  'Netherlands': { fifaCode: 'NED', name: 'Holanda', flag: '🇳🇱' },
  'Japan': { fifaCode: 'JPN', name: 'Japão', flag: '🇯🇵' },
  'Sweden': { fifaCode: 'SWE', name: 'Suécia', flag: '🇸🇪' },
  'Tunisia': { fifaCode: 'TUN', name: 'Tunísia', flag: '🇹🇳' },
  'Belgium': { fifaCode: 'BEL', name: 'Bélgica', flag: '🇧🇪' },
  'Egypt': { fifaCode: 'EGY', name: 'Egito', flag: '🇪🇬' },
  'Iran': { fifaCode: 'IRN', name: 'Irã', flag: '🇮🇷' },
  'New Zealand': { fifaCode: 'NZL', name: 'Nova Zelândia', flag: '🇳🇿' },
  'Spain': { fifaCode: 'ESP', name: 'Espanha', flag: '🇪🇸' },
  'Cape Verde': { fifaCode: 'CPV', name: 'Cabo Verde', flag: '🇨🇻' },
  'Saudi Arabia': { fifaCode: 'KSA', name: 'Arábia Saudita', flag: '🇸🇦' },
  'Uruguay': { fifaCode: 'URU', name: 'Uruguai', flag: '🇺🇾' },
  'France': { fifaCode: 'FRA', name: 'França', flag: '🇫🇷' },
  'Senegal': { fifaCode: 'SEN', name: 'Senegal', flag: '🇸🇳' },
  'Iraq': { fifaCode: 'IRQ', name: 'Iraque', flag: '🇮🇶' },
  'Norway': { fifaCode: 'NOR', name: 'Noruega', flag: '🇳🇴' },
  'Argentina': { fifaCode: 'ARG', name: 'Argentina', flag: '🇦🇷' },
  'Algeria': { fifaCode: 'ALG', name: 'Argélia', flag: '🇩🇿' },
  'Austria': { fifaCode: 'AUT', name: 'Áustria', flag: '🇦🇹' },
  'Jordan': { fifaCode: 'JOR', name: 'Jordânia', flag: '🇯🇴' },
  'Portugal': { fifaCode: 'POR', name: 'Portugal', flag: '🇵🇹' },
  'DR Congo': { fifaCode: 'COD', name: 'RD Congo', flag: '🇨🇩' },
  'Uzbekistan': { fifaCode: 'UZB', name: 'Uzbequistão', flag: '🇺🇿' },
  'Colombia': { fifaCode: 'COL', name: 'Colômbia', flag: '🇨🇴' },
  'England': { fifaCode: 'ENG', name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  'Croatia': { fifaCode: 'CRO', name: 'Croácia', flag: '🇭🇷' },
  'Ghana': { fifaCode: 'GHA', name: 'Gana', flag: '🇬🇭' },
  'Panama': { fifaCode: 'PAN', name: 'Panamá', flag: '🇵🇦' },
};
